### ISSUE TITLE
Fails when performance data has Infinity value

### ISSUE THREAD

**Issue by professoruss** [zorkian/nagios-api#59]
/dev[2015/09/22 19:11:54] {diesel} ERROR|-- Unhandled Exception in local loop <<function read_status at 0x3288140>> --
Traceback (most recent call last):
  File "/usr/local/lib/python2.6/site-packages/diesel/core.py", line 195, in run
    self.loop_callable(*self.args, **self.kw)
  File "/srv/nagios-api/nagios-api", line 833, in read_status
    NAGIOS = Nagios(statusfile)
  File "/srv/nagios-api/nagios/core.py", line 21, in __init__
    self._update(statusfile)
  File "/srv/nagios-api/nagios/core.py", line 72, in _update
    for obj in next_stanza(f):
  File "/srv/nagios-api/nagios/core.py", line 58, in next_stanza
    if (n_val == int(n_val)):
OverflowError: cannot convert float infinity to integer
[2015/09/22 19:11:54] {diesel} WARNING|(Keep-Alive loop <Loop id=1 callable=<function read_status at 0x3288140>> died; restarting)

**Comment by professoruss** [comment]
Thanks!
